apiVersion: "v1"
kind: "Service"
metadata:
  name: "api-service-deployment-service"
  namespace: "default"
  labels:
    app: "api-service"
    tier: "api-tier"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8888
  selector:
    app: "api-service"
    tier: "api-tier"
  type: "LoadBalancer"
  loadBalancerIP: ""
