apiVersion: v1
kind: Pod
metadata:
  name: api-service-deployment
  labels:
    app: api-service
    tier: api-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
      tier: api-tier
  template:
    metadata:
      labels:
        app: api-service
        tier: api-tier
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api-service-deployment
          image: xcodemaker/api_service:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8888