apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-deployment
  labels:
    app: data-service
    tier: data-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
      tier: data-tier
  template:
    metadata:
      labels:
        app: data-service
        tier: data-tier
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: data-service-deployment
          image: xcodemaker/data_service:latest
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 80