apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-deployment
  labels:
    app: data-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service-app
  template:
    metadata:
      labels:
        app: data-service-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: data-htttp-service
          image: xcodemaker/data_service:latest
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8000