apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  selector:
    app: data-service-deployment
    tier: data-tier
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
  type: NodePort